import {FormEvent,useEffect,useState} from 'react'
import {Activity,Archive,BookOpen,ChevronRight,CircleGauge,FileText,FolderOpen,KeyRound,LockKeyhole,Mail,Menu,RefreshCw,ScrollText,Send,Server,Settings,ShieldCheck,TerminalSquare,Users,X} from 'lucide-react'
import {api} from './api'
import {AccountsManagerPage,ApiKeysManagerPage,DashboardManagerPage,DiagnosticsManagerPage,FacebookManagerPage,MailBrowserManager,PermissionsManagerPage} from './AdminPages'

const nav=[['Dashboard',CircleGauge],['Comptes mail',Users],['Dossiers',FolderOpen],['Messages',Mail],['Configuration MCP',Server],['Facebook',Send],['Sécurité',ShieldCheck],['Clients OAuth',KeyRound],['Sessions OAuth',Users],['API Keys',KeyRound],['Permissions',LockKeyhole],['Logs',FileText],['Audit',ScrollText],['Diagnostics',Activity],['Test MCP',TerminalSquare],['Configuration système',Settings],['À propos',BookOpen]] as const
export function accountSlug(value:string){return value.normalize('NFKD').replace(/[\u0300-\u036f]/g,'').trim().replace(/[^a-zA-Z0-9_-]+/g,'-').replace(/^[-_]+|[-_]+$/g,'').toLowerCase().slice(0,100)}

function Login({done}:{done:()=>void}){const [error,setError]=useState('');async function submit(e:FormEvent<HTMLFormElement>){e.preventDefault();const fd=new FormData(e.currentTarget);try{await api('/auth/login',{method:'POST',body:JSON.stringify({username:fd.get('username'),password:fd.get('password')})});done()}catch(x){setError(String(x))}}return <main className="login"><div className="login-art"><div className="brand-mark"><Mail/></div><h1>Votre messagerie.<br/><span>Sous contrôle.</span></h1><p>Administration sécurisée de votre passerelle MCP Mail, en toute autonomie.</p><div className="protocol">MCP <i/> IMAP <i/> SMTP</div></div><form className="login-card" onSubmit={submit}><div className="eyebrow">LFINFO · MAIL MCP</div><h2>Connexion administrateur</h2><p>Accédez à votre espace de supervision.</p><label>Identifiant<input name="username" autoComplete="username" required autoFocus/></label><label>Mot de passe<input type="password" name="password" autoComplete="current-password" required/></label>{error&&<div className="error">Identifiants invalides ou configuration incomplète.</div>}<button>Se connecter <ChevronRight size={18}/></button><small><ShieldCheck size={14}/> Session chiffrée · Protection CSRF</small></form></main>}


type OAuthClientRow={client_id:string;client_name:string;redirect_uris:string[];allowed_scopes:string[];token_endpoint_auth_method:string;revoked_at?:string}
function OAuthClientsPage(){const [rows,setRows]=useState<OAuthClientRow[]>([]);const load=()=>api<OAuthClientRow[]>('/oauth/clients').then(setRows);useEffect(()=>{void load()},[]);async function revoke(id:string){if(!confirm('Révoquer ce client et toutes ses sessions ?'))return;await api(`/oauth/clients/${encodeURIComponent(id)}`,{method:'DELETE'});load()}return <><Header eyebrow="OAuth 2.1" title="Clients OAuth" text="Clients enregistrés dynamiquement, URI exactes et scopes autorisés."/><section className="panel table-panel"><table><thead><tr><th>Client</th><th>Redirections</th><th>Scopes</th><th>Authentification</th><th/></tr></thead><tbody>{rows.map(x=><tr key={x.client_id}><td><b>{x.client_name}</b><small><code>{x.client_id.slice(0,18)}…</code></small></td><td>{x.redirect_uris.map(u=><small key={u}>{u}</small>)}</td><td>{x.allowed_scopes.map(s=><span className="pill" key={s}>{s}</span>)}</td><td>{x.token_endpoint_auth_method}</td><td><button className="ghost" disabled={!!x.revoked_at} onClick={()=>revoke(x.client_id)}>{x.revoked_at?'Révoqué':'Révoquer'}</button></td></tr>)}</tbody></table></section></>}
type OAuthSessionRow={id:string;client_id:string;user?:string;scopes:string[];ip?:string;user_agent?:string;last_used_at:string;expires_at:string;revoked_at?:string}
function OAuthSessionsPage(){const [rows,setRows]=useState<OAuthSessionRow[]>([]);const load=()=>api<OAuthSessionRow[]>('/oauth/sessions').then(setRows);useEffect(()=>{void load()},[]);async function revoke(id:string){await api(`/oauth/sessions/${encodeURIComponent(id)}`,{method:'DELETE'});load()}return <><Header eyebrow="OAuth 2.1" title="Sessions OAuth" text="Consentements actifs, portée accordée, dernière utilisation et révocation immédiate."/><section className="panel table-panel"><table><thead><tr><th>Utilisateur</th><th>Client</th><th>Scopes</th><th>Dernière utilisation</th><th>Origine</th><th/></tr></thead><tbody>{rows.map(x=><tr key={x.id}><td><b>{x.user??'—'}</b></td><td><code>{x.client_id.slice(0,14)}…</code></td><td>{x.scopes.map(s=><span className="pill" key={s}>{s}</span>)}</td><td>{new Date(x.last_used_at).toLocaleString('fr-BE')}<small>Expire {new Date(x.expires_at).toLocaleDateString('fr-BE')}</small></td><td>{x.ip??'—'}<small>{x.user_agent}</small></td><td><button className="ghost" disabled={!!x.revoked_at} onClick={()=>revoke(x.id)}>{x.revoked_at?'Révoquée':'Révoquer'}</button></td></tr>)}</tbody></table></section></>}
function McpTest(){const [key,setKey]=useState('');const [method,setMethod]=useState('initialize');const [output,setOutput]=useState('');const [session,setSession]=useState('—');async function run(){const body:object=method==='initialize'?{jsonrpc:'2.0',id:1,method,params:{protocolVersion:'2025-03-26',capabilities:{},clientInfo:{name:'web-console',version:'1.0'}}}:{jsonrpc:'2.0',id:2,method,params:{}};const headers:Record<string,string>={'Content-Type':'application/json','Accept':'application/json, text/event-stream'};if(key)headers.Authorization=`Bearer ${key}`;if(session!=='—')headers['Mcp-Session-Id']=session;const r=await fetch('/mcp',{method:'POST',headers,body:JSON.stringify(body)});setSession(r.headers.get('Mcp-Session-Id')??session);setOutput(await r.text())}return <><Header eyebrow="Console intégrée" title="Test MCP" text="Initialisez une session et inspectez les réponses JSON-RPC."/><section className="panel tester"><div><label>Clé ou Bearer token<input type="password" value={key} onChange={e=>setKey(e.target.value)} placeholder="mcp_…"/></label><label>Méthode<select value={method} onChange={e=>setMethod(e.target.value)}><option>initialize</option><option>tools/list</option></select></label><button className="primary" onClick={run}><Send/>Exécuter</button><p>Session MCP : <code>{session}</code></p></div><pre>{output||'La réponse apparaîtra ici.'}</pre></section></>}


type LogRow={id:number;timestamp:string;tool?:string;action?:string;account?:string;actor?:string;duration_ms?:number;success:boolean;ip?:string;error?:string}
function LogsPage({audit=false}:{audit?:boolean}){const [rows,setRows]=useState<LogRow[]>([]);const [failed,setFailed]=useState(false);const load=()=>api<LogRow[]>(audit?'/audit':'/logs').then(setRows).catch(()=>setFailed(true));useEffect(()=>{void load()},[audit]);return <><Header eyebrow="Traçabilité" title={audit?'Audit':'Logs MCP'} text={audit?'Opérations sensibles et changements administratifs.':'Appels structurés, durées, sessions et erreurs sans corps de mail.'} action={<button className="primary" onClick={load}><RefreshCw/>Actualiser</button>}/>{failed&&<div className="error block">Impossible de charger le journal.</div>}<section className="panel table-panel"><table><thead><tr><th>Date</th><th>Opération</th><th>Compte</th><th>Acteur / IP</th><th>Durée</th><th>Résultat</th><th>Erreur</th></tr></thead><tbody>{rows.map(r=><tr key={r.id}><td>{new Date(r.timestamp).toLocaleString('fr-BE')}</td><td><code>{r.tool??r.action}</code></td><td>{r.account??'—'}</td><td>{r.actor??'—'}<small>{r.ip}</small></td><td>{r.duration_ms!==undefined?`${r.duration_ms} ms`:'—'}</td><td><span className={`pill ${r.success?'ok':''}`}>{r.success?'Succès':'Échec'}</span></td><td>{r.error??'—'}</td></tr>)}</tbody></table></section></>}

function ConfigurationPage({security=false}:{security?:boolean}){const [c,setC]=useState<Record<string,unknown>>({});useEffect(()=>{api<Record<string,unknown>>('/configuration').then(setC)},[]);const entries=security?Object.entries(c).filter(([k])=>/allowed|trusted|read_only|destructive|secret|attachment/.test(k)):Object.entries(c);return <><Header eyebrow="Paramètres actifs" title={security?'Sécurité':'Configuration MCP'} text="Valeurs chargées depuis l’environnement au démarrage; les secrets ne sont jamais exposés."/><section className="panel config-list">{entries.map(([k,v])=><div key={k}><span>{k.replaceAll('_',' ')}</span><code>{typeof v==='object'?JSON.stringify(v):String(v)}</code></div>)}</section></>}
function AboutPage(){return <><Header eyebrow="LFINFO" title="À propos" text="Passerelle Mail MCP self-hosted, conçue pour Mailcow et les serveurs standards."/><section className="panel about"><div className="brand-mark"><Mail/></div><h2>LFINFO Mail MCP <span>v1.0.0</span></h2><p>FastAPI · SDK MCP officiel · Streamable HTTP · SQLAlchemy · React · PM2</p><div className="protocol">MCP <i/> IMAP <i/> SMTP</div></section></>}
function Generic({name}:{name:string}){const copy:Record<string,string>={'Dossiers':'Parcourez l’arborescence canonique et les dossiers RFC 6154.','Messages':'Recherchez et consultez les messages de vos comptes.','Configuration MCP':'Contrôlez le transport, les origines, limites et URL publique.','Sécurité':'Surveillez l’authentification, le chiffrement et le mode lecture seule.','Permissions':'Matrice des capacités read, send, move, copy, flags, delete, folders et attachments.','Logs':'Journal structuré des appels MCP sans contenu de message.','Audit':'Traçabilité séparée des opérations sensibles.','Configuration système':'Paramètres actifs issus de l’environnement.','À propos':'LFINFO Mail MCP — passerelle self-hosted IMAP/SMTP.'};return <><Header eyebrow="Administration" title={name} text={copy[name]??''}/><section className="panel"><Empty title={`${name} prêt`} text="Cette vue utilise les API sécurisées de la plateforme. Consultez la documentation pour les opérations avancées."/></section></>}

export default function App(){const [auth,setAuth]=useState<boolean|null>(null);const [page,setPage]=useState('Dashboard');const [open,setOpen]=useState(false);useEffect(()=>{api('/dashboard').then(()=>setAuth(true)).catch(()=>setAuth(false))},[]);if(auth===null)return <Loader/>;if(!auth)return <Login done={()=>setAuth(true)}/>;const pages:Record<string,React.ReactNode>={'Dashboard':<DashboardManagerPage go={setPage}/>,'Comptes mail':<AccountsManagerPage/>,'Dossiers':<MailBrowserManager mode="folders"/>,'Messages':<MailBrowserManager mode="messages"/>,'Configuration MCP':<ConfigurationPage/>,'Facebook':<FacebookManagerPage/>,'Sécurité':<ConfigurationPage security/>,'Clients OAuth':<OAuthClientsPage/>,'Sessions OAuth':<OAuthSessionsPage/>,'API Keys':<ApiKeysManagerPage/>,'Permissions':<PermissionsManagerPage/>,'Logs':<LogsPage/>,'Audit':<LogsPage audit/>,'Diagnostics':<DiagnosticsManagerPage/>,'Test MCP':<McpTest/>,'Configuration système':<ConfigurationPage/>,'À propos':<AboutPage/>};const content=pages[page]??<Generic name={page}/>;return <div className="shell"><aside className={open?'open':''}><div className="logo"><span><Mail/></span><div>LFINFO<b>Mail MCP</b></div><button onClick={()=>setOpen(false)}><X/></button></div><nav>{nav.map(([label,Icon])=><button className={page===label?'active':''} key={label} onClick={()=>{setPage(label);setOpen(false)}}><Icon/>{label}</button>)}</nav><div className="aside-foot"><div className="live"><i/>Système opérationnel</div><small>v1.0.0 · Production</small></div></aside><div className="workspace"><header className="top"><button className="mobile" onClick={()=>setOpen(true)}><Menu/></button><div className="crumb">Administration <ChevronRight/> <b>{page}</b></div><button className="operator logout" title="Se déconnecter" onClick={async()=>{await api('/auth/logout',{method:'POST'});setAuth(false)}}><span>AD</span><div><b>Administrateur</b><small>Se déconnecter</small></div></button></header><main className="content">{content}</main></div></div>}
function Header({eyebrow,title,text,action}:{eyebrow:string;title:string;text:string;action?:React.ReactNode}){return <div className="page-head"><div><div className="eyebrow">{eyebrow}</div><h1>{title}</h1><p>{text}</p></div>{action}</div>}
function Empty({title,text}:{title:string;text:string}){return <div className="empty"><Archive/><b>{title}</b><p>{text}</p></div>}
function Loader(){return <div className="loader"><Mail/><span/></div>}
export function duration(s:number){const d=Math.floor(s/86400),h=Math.floor(s%86400/3600),m=Math.floor(s%3600/60);return `${d}j ${h}h ${m}m`}
